auto_prepend_file = /var/www/html/docker/php-prepend.php
display_errors = Off
log_errors = On

; Sessão: garantir que persiste no container
session.save_handler = files
session.save_path = "/tmp"
session.gc_maxlifetime = 86400
session.cookie_lifetime = 86400
